spice_mix = set ()
print (f"Initial spice_mix ID: {id(spice_mix)}")
print (f"Initial spice_mix ID: {spice_mix}")
spice_mix.add ("Ginger")
spice_mix.add ("Cardamom")
print (f"Initial spice_mix ID: {spice_mix}")
print (f"After spice_mix ID: {id(spice_mix)}")